spec:
  template:
    spec:
    - name: YOUR_CONTAINER_NAME
      volumeMounts:
      - name: config-volume
        mountPath: /opt/data
    volumes:
    - name: config-volume
      configMap:
        name: CONFIG_MAP_NAME
